suppress_self_cert_warning: true
auto_copy_stagers: true
mouse_support: false
servers:
  localhost:
    host: http://localhost
    port: 1337
    username: empireadmin
    password: password123
    autoconnect: true
#  other-server:
#    host: http://localhost
#    port: 1337
#    username: empireadmin
#    password: password123
directories:
  downloads: empire/client/downloads/
  generated_stagers: empire/client/generated-stagers/
tables:
  borders: true
logging:
  level: INFO
  directory: empire/client/downloads/logs/
